print "======================================"
print "Author : Swity"
print "Contac me :089699989010"
print "Cyber Layers Team"
print "please subscribe our youtube channel"
print "CyberLayersTeam"
print "======================================"
print "error 404"
print "Lu kebanyakan Coly"
